// A comprehensive list of common and useful medicine names for the Study Clock randomizer.
export const medicinesList = [
    "Acetaminophen", "Ibuprofen", "Aspirin", "Naproxen", "Diclofenac", "Celecoxib", "Meloxicam", 
    "Tramadol", "Codeine", "Morphine", "Oxycodone", "Hydrocodone", "Fentanyl", "Buprenorphine", 
    "Methadone", "Gabapentin", "Pregabalin", "Carbamazepine", "Topiramate", "Lamotrigine", 
    "Levetiracetam", "Phenytoin", "Valproic Acid", "Diazepam", "Lorazepam", "Alprazolam", 
    "Clonazepam", "Midazolam", "Zolpidem", "Eszopiclone", "Zaleplon", "Ramelteon", "Suvorexant", 
    "Amitriptyline", "Nortriptyline", "Imipramine", "Desipramine", "Fluoxetine", "Sertraline", 
    "Paroxetine", "Citalopram", "Escitalopram", "Fluvoxamine", "Venlafaxine", "Duloxetine", 
    "Desvenlafaxine", "Bupropion", "Mirtazapine", "Trazodone", "Aripiprazole", "Quetiapine", 
    "Risperidone", "Olanzapine", "Ziprasidone", "Lurasidone", "Haloperidol", "Chlorpromazine", 
    "Fluphenazine", "Lithium", "Divalproex", "Methylphenidate", "Amphetamine", "Dexmethylphenidate", 
    "Lisdexamfetamine", "Atomoxetine", "Guanfacine", "Levodopa", "Carbidopa", "Ropinirole", 
    "Pramipexole", "Rotigotine", "Entacapone", "Selegiline", "Rasagiline", "Amantadine", 
    "Donepezil", "Rivastigmine", "Galantamine", "Memantine", "Sumatriptan", "Rizatriptan", 
    "Zolmitriptan", "Eletriptan", "Naratriptan", "Frovatriptan", "Almotriptan", "Ergotamine", 
    "Metoprolol", "Atenolol", "Propranolol", "Bisoprolol", "Carvedilol", "Nebivolol", "Lisinopril", 
    "Enalapril", "Ramipril", "Benazepril", "Quinapril", "Losartan", "Valsartan", "Irbesartan", 
    "Candesartan", "Olmesartan", "Amlodipine", "Nifedipine", "Diltiazem", "Verapamil", 
    "Hydrochlorothiazide", "Chlorthalidone", "Furosemide", "Torsemide", "Bumetanide", 
    "Spironolactone", "Eplerenone", "Clonidine", "Doxazosin", "Terazosin", "Prazosin", 
    "Hydralazine", "Minoxidil", "Atorvastatin", "Rosuvastatin", "Simvastatin", "Pravastatin", 
    "Lovastatin", "Ezetimibe", "Fenofibrate", "Gemfibrozil", "Niacin", "Colesevelam", 
    "Cholestyramine", "Alirocumab", "Evolocumab", "Isosorbide Mononitrate", "Nitroglycerin", 
    "Amiodarone", "Sotalol", "Flecainide", "Propafenone", "Dofetilide", "Digoxin", "Warfarin", 
    "Rivaroxaban", "Apixaban", "Dabigatran", "Edoxaban", "Heparin", "Enoxaparin", "Fondaparinux", 
    "Clopidogrel", "Prasugrel", "Ticagrelor", "Albuterol", "Levalbuterol", "Salmeterol", 
    "Formoterol", "Fluticasone", "Budesonide", "Beclomethasone", "Mometasone", "Ciclesonide", 
    "Montelukast", "Zafirlukast", "Tiotropium", "Ipratropium", "Umeclidinium", "Aclidinium", 
    "Theophylline", "Omeprazole", "Pantoprazole", "Lansoprazole", "Esomeprazole", "Rabeprazole", 
    "Famotidine", "Ranitidine", "Cimetidine", "Sucralfate", "Bismuth Subsalicylate", "Ondansetron", 
    "Granisetron", "Palonosetron", "Promethazine", "Prochlorperazine", "Metoclopramide", "Droperidol", 
    "Aprepitant", "Docusate", "Senna", "Bisacodyl", "Polyethylene Glycol", "Lactulose", "Loperamide", 
    "Diphenoxylate", "Levothyroxine", "Liothyronine", "Methimazole", "Propylthiouracil", "Metformin", 
    "Glipizide", "Glimepiride", "Glyburide", "Pioglitazone", "Sitagliptin", "Saxagliptin", 
    "Linagliptin", "Canagliflozin", "Dapagliflozin", "Empagliflozin", "Exenatide", "Liraglutide", 
    "Dulaglutide", "Semaglutide", "Insulin Glargine", "Insulin Detemir", "Insulin Lispro", 
    "Insulin Aspart", "Insulin Regular", "Estradiol", "Conjugated Estrogens", "Progesterone", 
    "Medroxyprogesterone", "Testosterone", "Alendronate", "Risedronate", "Ibandronate", 
    "Zoledronic Acid", "Denosumab", "Teriparatide", "Raloxifene", "Allopurinol", "Febuxostat", 
    "Colchicine", "Probenecid", "Amoxicillin", "Ampicillin", "Penicillin V", "Cephalexin", 
    "Cefdinir", "Cefuroxime", "Ceftriaxone", "Azithromycin", "Clarithromycin", "Erythromycin", 
    "Ciprofloxacin", "Levofloxacin", "Moxifloxacin", "Doxycycline", "Minocycline", 
    "Sulfamethoxazole", "Trimethoprim", "Metronidazole", "Clindamycin", "Nitrofurantoin", 
    "Fluconazole", "Ketoconazole", "Itraconazole", "Voriconazole", "Terbinafine", "Acyclovir", 
    "Valacyclovir", "Famciclovir", "Oseltamivir", "Prednisone", "Methylprednisolone", 
    "Dexamethasone", "Hydrocortisone", "Fludrocortisone", "Methotrexate", "Adalimumab", 
    "Etanercept", "Infliximab", "Rituximab", "Sildenafil", "Tadalafil", "Vardenafil", 
    "Epinephrine", "Atropine", "Adenosine", "Dopamine", "Dobutamine", "Norepinephrine", 
    "Vasopressin", "Phenylephrine", "Nitropresside", "Propofol", "Ketamine", "Etomidate", 
    "Rocuronium", "Vecuronium", "Succinylcholine", "Neostigmine", "Sugammadex"
];
